name: Build Android APK

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Setup Java (needed for Android/Gradle)
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      # Setup Flutter
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.22.2"
          channel: "stable"

      # Create a new Flutter app in a subfolder (scaffold Gradle project)
      - name: Scaffold Flutter app
        run: flutter create -t app behemoth_slayer_app --platforms=android

      # Inject our Behemoth Slayer scaffold UI
      - name: Inject app code
        run: |
          cat > behemoth_slayer_app/lib/main.dart <<'EOF'
import 'package:flutter/material.dart';

void main() => runApp(const BehemothApp());

class BehemothApp extends StatelessWidget {
  const BehemothApp({super.key});

  @override
  Widget build(BuildContext context) {
    final theme = ThemeData(
      brightness: Brightness.dark,
      scaffoldBackgroundColor: const Color(0xFF0B0F14),
      colorScheme:
